- name: install zsh
  apt: name=zsh state=latest update_cache=yes cache_valid_time=600
  when: "'Debian' in ansible_distribution or 'Ubuntu' in ansible_distribution or 'mint' in ansible_distribution"

- name: install zsh
  pacman: name=zsh state=present
  when: "'Arch' in ansible_distribution or 'Manjaro' in ansible_distribution"

- name: set zsh as default shell
  command: chsh -s '/bin/zsh' {{ main_user_name }}
