- name: downlod source code
  git: 
    repo: https://github.com/direnv/direnv.git
    dest: /home/{{ main_user_name }}/usr/src/direnv
    depth: 1
    version: "{{ version }}"
  become: no

- name: install
  command: "make -j{{ ansible_processor_count * 2 }} install chdir=/home/{{ main_user_name }}/usr/src/direnv"
  environment:
    DESTDIR: "/home/{{ main_user_name }}/usr"
  become: no
