- name: install python packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - python3-pip
    - python3-setuptools
    - python-pip
    - python-setuptools
  when: "'Debian' in ansible_distribution or 'Ubuntu' in ansible_distribution or 'mint' in ansible_distribution"

- name: install python packages
  pacman: name={{ item }} state=present
  with_items:
    - python-pip
    - python-setuptools
  when: "'Arch' in ansible_distribution or 'Manjaro' in ansible_distribution"
