- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - system_base
    - system_admin
    - user
    - user_utilities
    - desktop
    - develop
    - multi_media
  become: true
  tasks:
