- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - groups/user
    - groups/user_utilities
    - groups/fonts
    - groups/desktop
    - groups/develop
  become: true
  tasks:
