dependencies:
  - { role: packages/docker }
  - { role: packages/docker-compose }
  - { role: packages/node_npm }
  - { role: packages/neovim }
  - { role: packages/emacs }
  - { role: packages/terraform }
  - { role: packages/rust }
