- name: download rustup script
  become: false
  get_url:
    url: https://sh.rustup.rs 
    dest: /tmp/rustup.sh
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
    mode: 0700

- name: exec rustup
  become: false
  script: /tmp/rustup.sh -y

- name: update to nightly
  become: false
  command: "rustup update nightly --force"
  environment:
    PATH: /home/{{ main_user_name }}/.cargo/bin/:{{ ansible_env.PATH }}


- name: install rust develop helper packages
  become: false
  command: "cargo +nightly install {{ item }} --force"
  environment:
    PATH: /home/{{ main_user_name }}/.cargo/bin/:{{ ansible_env.PATH }}
  with_items:
    - rustfmt
    - racer

- name: download rust-src
  become: false
  command: "/home/{{ main_user_name }}/.cargo/bin/rustup component add rust-src"
