- name: install docker-compose
  apt: name=docker-compose state=latest update_cache=yes cache_valid_time=600
  when: "'Debian' in ansible_distribution or 'Ubuntu' in ansible_distribution or 'mint' in ansible_distribution"

- name: install docker-compose
  pacman: name=docker-compose state=present
  when: "'Arch' in ansible_distribution or 'Manjaro' in ansible_distribution"
