- name: install go
  apt: name=golang state=latest update_cache=yes cache_valid_time=600
  when: "'Debian' in ansible_distribution or 'Ubuntu' in ansible_distribution or 'mint' in ansible_distribution"

- name: install go
  pacman: name=go state=present
  when: "'Arch' in ansible_distribution or 'Manjaro' in ansible_distribution"

- name: install go develop helper packages
  command: "go get -u -v {{ item }}"
  become: false
  environment:
    GOPATH: /home/{{ main_user_name }}/usr/lib/go # note: exists duplicated definition => roles/packages/oh-my-zsh
  with_items:
    - github.com/nsf/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/guru
    - golang.org/x/tools/cmd/gorename
    - golang.org/x/tools/cmd/goimports
    - github.com/alecthomas/gometalinter

- name: update gometalinter
  command: "gometalinter --install --update"
  become: false
  environment:
    PATH: /home/{{ main_user_name }}/usr/lib/go/bin:{{ ansible_env.PATH }}
    GOPATH: /home/{{ main_user_name }}/usr/lib/go # note: exists duplicated definition => roles/packages/oh-my-zsh
