- name: install dependency libs for building neovim
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
  when: "'Debian' in ansible_distribution or 'Ubuntu' in ansible_distribution or 'mint' in ansible_distribution"

- name: install dependency libs for building neovim
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - cmake
    - unzip
  when: "'Arch' in ansible_distribution or 'Manjaro' in ansible_distribution"

- name: downlod source code
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /home/{{ main_user_name }}/usr/src/neovim
    depth: 1
    version: "{{ version }}"
  become: no

- name: permission
  file:
    dest: /home/{{ main_user_name }}/usr/src/neovim
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
    recurse: yes
  become: no

- name: distclean
  make:
    chdir: /home/{{ main_user_name }}/usr/src/neovim
    target: distclean
  become: no

- name: build
  command: "make CMAKE_BUILD_TYPE=Release -j{{ ansible_processor_count * 2 }} CMAKE_EXTRA_FLAGS='-DCMAKE_INSTALL_PREFIX:PATH=/home/{{ main_user_name }}/usr' chdir=/home/{{ main_user_name }}/usr/src/neovim"
  become: no

- name: install
  make:
    chdir: /home/{{ main_user_name }}/usr/src/neovim
    target: install
  become: no

- name: cleanup1
  make:
    chdir: /home/{{ main_user_name }}/usr/src/neovim
    target: clean
  become: no

- name: cleanup2
  file:
    path: /home/{{ main_user_name }}/usr/src/neovim/build
    state: absent
  become: no

- name: Ensures conf dir exists
  file: path=/home/{{ main_user_name }}/.config/nvim state=directory
  become: no

- name: Ensures autoload dir exists
  file: path=/home/{{ main_user_name }}/.local/share/nvim/site/autoload state=directory
  become: no

- name: copy init script
  file:
    state: link
    force: yes
    src: "{{ repo_root }}/role/packages/neovim/files/init.vim"
    path: /home/{{ main_user_name }}/.config/nvim/init.vim
  become: no

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ main_user_name }}/.local/share/nvim/site/autoload/plug.vim
  become: no

- name: install python3 packages for neovim
  pip: name={{ item }} executable=pip3
  with_items:
    - neovim
    - websocket-client
    - sexpdata

- name: install python2 packages for neovim
  pip: name={{ item }} executable=pip2
  with_items:
    - neovim
