- name: downlod source code
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{ main_user_name }}/usr/src/oh-my-zsh
    depth: 1
    version: master
  become: no

- name: deploy oh-my-zsh
  file:
    src: /home/{{ main_user_name }}/usr/src/oh-my-zsh
    dest: /home/{{ main_user_name }}/.oh-my-zsh
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
    state: link
  become: no

- name: replace zshrc
  copy:
    src: /home/{{ main_user_name }}/usr/src/oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/{{ main_user_name }}/.zshrc
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
    remote_src: yes
  become: no

- name: change theme
  lineinfile: >
    dest='/home/{{ main_user_name }}/.zshrc'
    regexp='ZSH_THEME='
    line='ZSH_THEME=steeef'
  become: no

- name: include common script
  lineinfile: >
    dest='/home/{{ main_user_name }}/.zshrc'
    line='[[ -f ~/.zshrc.common ]] && source ~/.zshrc.common'
  become: no

- name: include local script
  lineinfile: >
    dest='/home/{{ main_user_name }}/.zshrc'
    line='[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local'
  become: no

- name: copy common zshrc
  file:
    state: link
    force: yes
    src: {{ repo_root }}/role/packages/oh-my-zsh/files/zshrc.common
    path: /home/{{ main_user_name }}/.zshrc.common
  become: no

- name: copy common zshenv
  file:
    state: link
    force: yes
    src: {{ repo_root }}/role/packages/oh-my-zsh/files/zshenv
    path: /home/{{ main_user_name }}/.zshenv
  become: no
