- name: include docker task
  include: roles/packages/docker/main.yml

- name: include docker-compose task
  include: roles/packages/docker-compose/main.yml

- name: belong to docker group
  user: 
    name: "{{ main_user_name }}"
    groups: docker
    append: yes

- name: enable docker
  shell: systemctl enable docker.service
