- name: Ensures conf dir exists
  file: path=/home/{{ main_user_name }}/.config/nvim state=directory
  become: no

- name: Ensures autoload dir exists
  file: path=/home/{{ main_user_name }}/.local/share/nvim/site/autoload state=directory
  become: no

- name: copy init script
  copy:
    src: init.vim
    dest: /home/{{ main_user_name }}/.config/nvim/init.vim
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
  become: no

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ main_user_name }}/.local/share/nvim/site/autoload/plug.vim
  become: no

- name: install python3 packages for neovim
  pip: name={{ item }} executable=pip3
  with_items:
    - neovim
    - websocket-client
    - sexpdata

- name: install python2 packages for neovim
  pip: name={{ item }} executable=pip2
  with_items:
    - neovim
