- name: Ensures conf dir exists
  file: path=/home/{{ main_user_name }}/.config/nvim state=directory

- name: Ensures autoload dir exists
  file: path=/home/{{ main_user_name }}/.local/share/nvim/site/autoload state=directory

- name: copy init script
  copy:
    src: init.vim
    dest: /home/{{ main_user_name }}/.config/nvim/init.vim
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ main_user_name }}/.local/share/nvim/site/autoload/plug.vim

- name: install python3-neovim
  pip: 
   name: neovim
   executable: pip3
